version: '3'

services:
  db:
    image: postgres:15.2-alpine3.17
    container_name: sov_db
    volumes:
      - ./Data/db/:/var/lib/postgresql/data
      - ./Data/initial/:/home/
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=duy
      - POSTGRES_PASSWORD=1
    ports:
      - "5432:5432"

  backend:
    container_name: sov_server
    build: ./Server_App
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Server_App:/src
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=db
      - POSTGRES_USER=duy
      - POSTGRES_PASSWORD=1
    tty: true
    depends_on:
      - db
    restart: always